force-app/main/default/objects/MJ_Monthly_Report__c/MJ_Monthly_Report__c.object-meta.xml
<CustomObject>
    <label>MJ Monthly Report</label>
    <nameField>
        <label>MJ Monthly Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MJ Monthly Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MJ_Monthly_Report__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>External Id to match records during upsert. This is a read-only field with the format: &lt;4 digit firmcode&gt;_&lt;Month_Year Field&gt;</inlineHelpText>
    <label>External Id</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MJ_Monthly_Report__c/fields/Firmcode__c.field-meta.xml
<CustomField>
    <fullName>Firmcode__c</fullName>
    <inlineHelpText>The MJ FirmCode related to the Account this Monthly Report belongs to</inlineHelpText>
    <label>Firmcode</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJ_Reporting_Metrics_Callout_Data__c/MJ_Reporting_Metrics_Callout_Data__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Custom Setting stores the MJMonthlyReportBatch data required for callouts like the access token, access token expiry datetime and last callout date time</description>
    <label>MJ Reporting Metrics Callout Data</label>
</CustomObject>

force-app/main/default/objects/MJ_Reporting_Metrics_Callout_Data__c/fields/accessToken__c.field-meta.xml
<CustomField>
    <fullName>accessToken__c</fullName>
    <inlineHelpText>MJ Reporting Token</inlineHelpText>
    <label>accessToken</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJ_Reporting_Metrics_Callout_Data__c/fields/Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Base_URL__c</fullName>
    <description>The base URL to callout MJ Reporting data</description>
    <label>Base URL</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJ_Reporting_Metrics_Callout_Data__c/fields/Expiry__c.field-meta.xml
<CustomField>
    <fullName>Expiry__c</fullName>
    <description>The Date Time when the current access token will expire</description>
    <label>Expiry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MJ_Reporting_Metrics_Callout_Data__c/fields/LastCallout__c.field-meta.xml
<CustomField>
    <fullName>LastCallout__c</fullName>
    <description>The DateTime when last callout was made</description>
    <label>Last Callout</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MJ_Reporting_Metrics_Callout_Data__c/fields/MJ_Middleware_Password__c.field-meta.xml
<CustomField>
    <fullName>MJ_Middleware_Password__c</fullName>
    <description>The password required to callout the Token to get the MJ Reporting token</description>
    <label>MJ Middleware Password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJ_Reporting_Metrics_Callout_Data__c/fields/MJ_Middleware_Username__c.field-meta.xml
<CustomField>
    <fullName>MJ_Middleware_Username__c</fullName>
    <description>The username for use to callout the Token for MJ Reporting</description>
    <label>MJ Middleware Username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MJMonthlyReportBatch.cls
public class MJMonthlyReportBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{

    public final String accessToken;
    public final DateTime expiry;
    public final String monthsToProcessString;
    public final MJ_Reporting_Metrics_Callout_Data__c calloutData;
    public final String BaseURL;

    public List<MJ_Monthly_Report__c> monthlyReportList;
	

   public MJMonthlyReportBatch(){

        monthlyReportList = new List<MJ_Monthly_Report__c>();

        // Access Custom Setting to get the callout data 
        calloutData = MJ_Reporting_Metrics_Callout_Data__c.getOrgDefaults();
       
        DateTime accessTokenExpiresAt = calloutData.Expiry__c;
        String accessToken = calloutData.accessToken__c;        
       
       // If current token or expiry date is null, get new token
       if(accessTokenExpiresAt == null || accessToken == null) {
           
            Map<String,Object> tokenMap = MJMonthlyReportHelper.postMJToken(calloutData.Base_URL__c, calloutData.MJ_Middleware_Username__c, calloutData.MJ_Middleware_Password__c);
        
            String dateTimeStr = (String) tokenMap.get('accessTokenExpiresAt');
            
         	// Set the instance vars to new Values
            accessToken = (String) tokenMap.get('accessToken');
         	accessTokenExpiresAt = MJMonthlyReportHelper.tokenExpiryDateParser(dateTimeStr); 
           
       } // If old token has only half an hour or less left till expiry date, get new token
      
       
       if ( accessTokenExpiresAt  < Datetime.now().addMinutes(30) ) {
            Map<String,Object> tokenMap = MJMonthlyReportHelper.postMJToken(calloutData.Base_URL__c, calloutData.MJ_Middleware_Username__c, calloutData.MJ_Middleware_Password__c);        
        	String dateTimeStr = (String) tokenMap.get('accessTokenExpiresAt');   

         	// Set the instance vars to new Values
            accessToken = (String) tokenMap.get('accessToken');
         	accessTokenExpiresAt = MJMonthlyReportHelper.tokenExpiryDateParser(dateTimeStr);          
       }
       
        this.accessToken = accessToken;
        this.expiry = accessTokenExpiresAt;
        this.BaseURL = calloutData.Base_URL__c;


        // Initialize monthsToProcess
        List<Date> monthsToProcess = new List<Date>();

        // Initialize month_year string List
        List<String> monthYearStrings = new List<String>();
       
        // Binding the last callout datetime to a temporary variable
        Datetime curCalloutStartDateTime = calloutData.LastCallout__c;

        // If last callout date is not available, use today as the last callout date
        if(curCalloutStartDateTime == null) curCalloutStartDateTime = Date.today();
    
        System.debug(curCalloutStartDateTime);


        // Set the temp variable to the 1st of the month/year of the last callout date
        curCalloutStartDateTime= Datetime.newInstanceGMT(
            curCalloutStartDateTime.year(), curCalloutStartDateTime.month(), 1
            );

            System.debug(curCalloutStartDateTime);

        /* 
        * The following loop collects placeholder dates for each month callout is required
        * 
        * For ex: lastcallout = 1/1/22
        * today =  1/7/22
        * 
		* then dates collected = {1/1/22,1/2/22,1/3/22,....,1/7/22}
        * 
        */

        // Iterate over each month from last callout to today
        while(
            curCalloutStartDateTime <= Datetime.now()
             ) {

            monthsToProcess.add(
                Date.newInstance(
                curCalloutStartDateTime.year(), 
                curCalloutStartDateTime.month(),
                1
            ));

            monthYearStrings.add( String.valueOf(curCalloutStartDateTime.month()) + '_' + String.valueOf(curCalloutStartDateTime.year()) );


            curCalloutStartDateTime = curCalloutStartDateTime.addMonths(1);

            // Loop to create list of Month_Year Strings i.e {'month1_Year1','month2_Year2','month3_Year3'...} etc.
        }

       // Create a string of month year strings
        monthsToProcessString = String.join(monthYearStrings, ',');

       System.debug(this.monthsToProcessString);
       System.debug(curCalloutStartDateTime);
       System.debug(Datetime.now());
       System.debug(monthsToProcessString);

    }


   public Database.QueryLocator start(Database.BatchableContext BC){

    // If no months gathered then abort job 
       if(this.monthsToProcessString == null) {
       	System.abortJob(BC.getJobId());
       }
       
       // If error in getting access token, abort job
       System.assert(this.accessToken!=null);
       
       System.debug(accessToken);
            
       System.debug(monthsToProcessString);
       
       String query = 'SELECT id, Name, firmcode__c from account WHERE Firmcode__c != NULL AND Active_MJ_Customer__c=TRUE';
       return Database.getQueryLocator(query);
   }

   public void execute(Database.BatchableContext BC, List<sObject> scope){
       System.debug(scope);
       
    MJMonthlyReportController controller = new MJMonthlyReportController(this.accessToken, this.monthsToProcessString, scope, this.BaseURL);
        monthlyReportList.addAll(controller.processMonthlyReportsForAccounts());

    }

   public void finish(Database.BatchableContext BC){

        System.debug(monthlyReportList);

        if(monthlyReportList.size() != 0) {
            try {
                upsert monthlyReportList External_Id__c;
            } catch (Exception e) {
                System.debug(e.getMessage());
            }       
       }

   	   calloutData.LastCallout__c = DateTime.Now();
       calloutData.accessToken__c = this.accessToken;
       calloutData.Expiry__c = this.expiry;
           
		upsert calloutData;
       
   }
}